title = "Vincent Goulet"
baseURL = "https://vigou3.gitlab.io/ulthese"
languageCode = "fr-ca"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
enableRobotsTXT = true

[params]
  ## Links
  pages_home = "https://vigou3.gitlab.io/fr"
  gitlab = "https://gitlab.com/vigou3"
  repos = "ulthese"

  ## Release information
  ctan = "https://ctan.org/pkg"
  version = "6.0"
  release_date = "2024-07-02"
  release_notes = "-/releases"
  archive_name = "ulthese-installation-projet.zip"
  archive_id = "https://gitlab.com/vigou3/ulthese/-/package_files/136061075/download"

  ## Look and feel
  custom_css = ["css/custom.css"]
  background_color_class = "bg-black"
  featured_image = "/images/csm_stade-telus-universite-laval-interieur-credit-peps_570905cc15.jpg"
  body_classes = "bg-near-white"

  ## Google Fonts integration using the implementation of
  ## https://jeremybise.com/google-fonts-in-hugo-themes/
  ##
  ## See also assets/scss/main.scss; layouts/partials/google-fonts.html;
  ## layouts/_default/baseof.html.
  google_fonts = [
    ["Fira Sans", "300, 300i, 400, 400i, 600, 600i"],
    ["Fira Code", "300"]
  ]
  heading_font = "Fira Sans"
  body_font = "Fira Sans"
  code_font = "Fira Code"
